version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - arbetsprov
  worker:
    build: ./worker
    depends_on:
      - db
    networks:
      - arbetsprov
  webservice:
    container_name: webservice
    build: ./webservice
    depends_on:
      - worker
    ports:
      - 3333:3333
    volumes:
      - lieroarbetsprov/webservice
    networks:
      - arbetsprov

networks:
  arbetsprov:
    driver: bridge
    name: arbetsprov
